name: Notify Discord on push

on:
  push:
    branches: ["main"]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          set -e
          commits=$(jq -r '.commits[].message' "$GITHUB_EVENT_PATH" | sed 's/^/- /')

          payload=$(jq -n \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg actor "${{ github.actor }}" \
            --arg branch "$GITHUB_REF_NAME" \
            --arg msg "$commits" \
            '{content: "**Repository:** \($repo)\n**Author:** \($actor)\n**Branch:** \($branch)\n\n**Recent commits:**\n\($msg)"}')

          curl -H "Content-Type: application/json" \
              -d "$payload" \
              "${{ secrets.DISCORD_WEBHOOK }}"